alias memorylamp="code ~/code/dart/memorylamp-mobile"
alias dating="code ~/code/dart/bw-dating-app"
alias church="code ~/code/javascript/church_information_system"
alias lofi="code ~/code/typescript/lofi-moods"
alias music="code ~/code/typescript/music"
